# coding: utf-8

"""
    Clash Royale API

    Check out <a href=\"https://developer.clashroyale.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash Royale API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashroyale.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "clashroyale.py"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Clash Royale API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Clash Royale API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Check out &lt;a href&#x3D;\&quot;https://developer.clashroyale.com/#/getting-started\&quot; target&#x3D;\&quot;_parent\&quot;&gt;Getting Started&lt;/a&gt; for instructions and links to other resources. Clash Royale API uses &lt;a href&#x3D;\&quot;https://jwt.io/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;JSON Web Tokens&lt;/a&gt; for authorizing the requests. Tokens are created by developers on &lt;a href&#x3D;\&quot;https://developer.clashroyale.com/#/account\&quot; target&#x3D;\&quot;_parent\&quot;&gt;My Account&lt;/a&gt; page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \&quot;Authorization: Bearer API_TOKEN\&quot;. 
    """,  # noqa: E501
    package_data={"clashroyale": ["py.typed"]},
)