# coding: utf-8

# flake8: noqa
"""
    Clash Royale API

    Check out <a href=\"https://developer.clashroyale.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash Royale API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashroyale.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from clashroyale.models.arena import Arena
from clashroyale.models.battle import Battle
from clashroyale.models.cancel_match_response import CancelMatchResponse
from clashroyale.models.challenge import Challenge
from clashroyale.models.challenge_chain import ChallengeChain
from clashroyale.models.challenge_game_mode import ChallengeGameMode
from clashroyale.models.chest import Chest
from clashroyale.models.clan import Clan
from clashroyale.models.clan_member import ClanMember
from clashroyale.models.clan_ranking import ClanRanking
from clashroyale.models.clan_war_clan import ClanWarClan
from clashroyale.models.clan_war_log_entry import ClanWarLogEntry
from clashroyale.models.clan_war_participant import ClanWarParticipant
from clashroyale.models.clan_war_standing import ClanWarStanding
from clashroyale.models.client_error import ClientError
from clashroyale.models.current_clan_war import CurrentClanWar
from clashroyale.models.current_river_race import CurrentRiverRace
from clashroyale.models.emote import Emote
from clashroyale.models.fingerprint import Fingerprint
from clashroyale.models.game_mode import GameMode
from clashroyale.models.item import Item
from clashroyale.models.items import Items
from clashroyale.models.ladder_tournament import LadderTournament
from clashroyale.models.ladder_tournament_ranking import LadderTournamentRanking
from clashroyale.models.leaderboard import Leaderboard
from clashroyale.models.league_season import LeagueSeason
from clashroyale.models.league_season_result import LeagueSeasonResult
from clashroyale.models.location import Location
from clashroyale.models.match import Match
from clashroyale.models.path_of_legend_season_result import PathOfLegendSeasonResult
from clashroyale.models.period_log import PeriodLog
from clashroyale.models.period_log_entry import PeriodLogEntry
from clashroyale.models.period_log_entry_clan import PeriodLogEntryClan
from clashroyale.models.player import Player
from clashroyale.models.player_achievement_badge import PlayerAchievementBadge
from clashroyale.models.player_achievement_progress import PlayerAchievementProgress
from clashroyale.models.player_battle_data import PlayerBattleData
from clashroyale.models.player_battle_round import PlayerBattleRound
from clashroyale.models.player_clan import PlayerClan
from clashroyale.models.player_item_level import PlayerItemLevel
from clashroyale.models.player_league_statistics import PlayerLeagueStatistics
from clashroyale.models.player_path_of_legend_ranking import PlayerPathOfLegendRanking
from clashroyale.models.player_ranking import PlayerRanking
from clashroyale.models.player_ranking_clan import PlayerRankingClan
from clashroyale.models.register_match_request import RegisterMatchRequest
from clashroyale.models.register_match_response import RegisterMatchResponse
from clashroyale.models.replay import Replay
from clashroyale.models.river_race_clan import RiverRaceClan
from clashroyale.models.river_race_log_entry import RiverRaceLogEntry
from clashroyale.models.river_race_participant import RiverRaceParticipant
from clashroyale.models.river_race_standing import RiverRaceStanding
from clashroyale.models.survival_milestone_reward import SurvivalMilestoneReward
from clashroyale.models.tournament import Tournament
from clashroyale.models.tournament_header import TournamentHeader
from clashroyale.models.tournament_member import TournamentMember
from clashroyale.models.upcoming_chests import UpcomingChests
from clashroyale.models.verify_token_request import VerifyTokenRequest
from clashroyale.models.verify_token_response import VerifyTokenResponse
from clashroyale.models.version import Version
