# coding: utf-8

"""
    Clash Royale API

    Check out <a href=\"https://developer.clashroyale.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash Royale API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashroyale.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clashroyale.models.challenge_game_mode import ChallengeGameMode
from clashroyale.models.survival_milestone_reward import SurvivalMilestoneReward
from typing import Optional, Set
from typing_extensions import Self

class Challenge(BaseModel):
    """
    Challenge
    """ # noqa: E501
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    win_mode: Optional[StrictStr] = Field(default=None, alias="winMode")
    casual: Optional[StrictBool] = None
    max_losses: Optional[StrictInt] = Field(default=None, alias="maxLosses")
    max_wins: Optional[StrictInt] = Field(default=None, alias="maxWins")
    icon_url: Optional[StrictStr] = Field(default=None, alias="iconUrl")
    game_mode: Optional[ChallengeGameMode] = Field(default=None, alias="gameMode")
    prizes: Optional[List[SurvivalMilestoneReward]] = None
    __properties: ClassVar[List[str]] = ["name", "description", "id", "winMode", "casual", "maxLosses", "maxWins", "iconUrl", "gameMode", "prizes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Challenge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of game_mode
        if self.game_mode:
            _dict['gameMode'] = self.game_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in prizes (list)
        _items = []
        if self.prizes:
            for _item_prizes in self.prizes:
                if _item_prizes:
                    _items.append(_item_prizes.to_dict())
            _dict['prizes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Challenge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "winMode": obj.get("winMode"),
            "casual": obj.get("casual"),
            "maxLosses": obj.get("maxLosses"),
            "maxWins": obj.get("maxWins"),
            "iconUrl": obj.get("iconUrl"),
            "gameMode": ChallengeGameMode.from_dict(obj["gameMode"]) if obj.get("gameMode") is not None else None,
            "prizes": [SurvivalMilestoneReward.from_dict(_item) for _item in obj["prizes"]] if obj.get("prizes") is not None else None
        })
        return _obj


