# coding: utf-8

"""
    Clash Royale API

    Check out <a href=\"https://developer.clashroyale.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash Royale API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashroyale.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clashroyale.models.arena import Arena
from clashroyale.models.player_ranking_clan import PlayerRankingClan
from typing import Optional, Set
from typing_extensions import Self

class PlayerRanking(BaseModel):
    """
    PlayerRanking
    """ # noqa: E501
    clan: Optional[PlayerRankingClan] = None
    arena: Optional[Arena] = None
    tag: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    exp_level: Optional[StrictInt] = Field(default=None, alias="expLevel")
    rank: Optional[StrictInt] = None
    previous_rank: Optional[StrictInt] = Field(default=None, alias="previousRank")
    trophies: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["clan", "arena", "tag", "name", "expLevel", "rank", "previousRank", "trophies"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayerRanking from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of clan
        if self.clan:
            _dict['clan'] = self.clan.to_dict()
        # override the default output from pydantic by calling `to_dict()` of arena
        if self.arena:
            _dict['arena'] = self.arena.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayerRanking from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clan": PlayerRankingClan.from_dict(obj["clan"]) if obj.get("clan") is not None else None,
            "arena": Arena.from_dict(obj["arena"]) if obj.get("arena") is not None else None,
            "tag": obj.get("tag"),
            "name": obj.get("name"),
            "expLevel": obj.get("expLevel"),
            "rank": obj.get("rank"),
            "previousRank": obj.get("previousRank"),
            "trophies": obj.get("trophies")
        })
        return _obj


