# coding: utf-8

"""
    Clash Royale API

    Check out <a href=\"https://developer.clashroyale.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash Royale API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashroyale.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from clashroyale.models.item import Item
from typing import Optional, Set
from typing_extensions import Self

class SurvivalMilestoneReward(BaseModel):
    """
    SurvivalMilestoneReward
    """ # noqa: E501
    rarity: Optional[StrictStr] = None
    chest: Optional[StrictStr] = None
    resource: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    amount: Optional[StrictInt] = None
    card: Optional[Item] = None
    consumable_name: Optional[StrictStr] = Field(default=None, alias="consumableName")
    wins: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["rarity", "chest", "resource", "type", "amount", "card", "consumableName", "wins"]

    @field_validator('rarity')
    def rarity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['common', 'rare', 'epic', 'legendary', 'champion']):
            raise ValueError("must be one of enum values ('common', 'rare', 'epic', 'legendary', 'champion')")
        return value

    @field_validator('resource')
    def resource_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['gold', 'unknown']):
            raise ValueError("must be one of enum values ('gold', 'unknown')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'card_stack', 'chest', 'card_stack_random', 'resource', 'trade_token', 'consumable']):
            raise ValueError("must be one of enum values ('none', 'card_stack', 'chest', 'card_stack_random', 'resource', 'trade_token', 'consumable')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SurvivalMilestoneReward from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of card
        if self.card:
            _dict['card'] = self.card.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SurvivalMilestoneReward from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rarity": obj.get("rarity"),
            "chest": obj.get("chest"),
            "resource": obj.get("resource"),
            "type": obj.get("type"),
            "amount": obj.get("amount"),
            "card": Item.from_dict(obj["card"]) if obj.get("card") is not None else None,
            "consumableName": obj.get("consumableName"),
            "wins": obj.get("wins")
        })
        return _obj


