# coding: utf-8

# flake8: noqa

"""
    Clash Royale API

    Check out <a href=\"https://developer.clashroyale.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash Royale API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashroyale.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.2"

# Define package exports
__all__ = [
    "CardsApi",
    "ChallengesApi",
    "ClansApi",
    "GlobaltournamentsApi",
    "LeaderboardsApi",
    "LocationsApi",
    "PlayersApi",
    "TournamentsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Arena",
    "Battle",
    "CancelMatchResponse",
    "Challenge",
    "ChallengeChain",
    "ChallengeGameMode",
    "Chest",
    "Clan",
    "ClanMember",
    "ClanRanking",
    "ClanWarClan",
    "ClanWarLogEntry",
    "ClanWarParticipant",
    "ClanWarStanding",
    "ClientError",
    "CurrentClanWar",
    "CurrentRiverRace",
    "Emote",
    "Fingerprint",
    "GameMode",
    "Item",
    "Items",
    "LadderTournament",
    "LadderTournamentRanking",
    "Leaderboard",
    "LeagueSeason",
    "LeagueSeasonResult",
    "Location",
    "Match",
    "PathOfLegendSeasonResult",
    "PeriodLog",
    "PeriodLogEntry",
    "PeriodLogEntryClan",
    "Player",
    "PlayerAchievementBadge",
    "PlayerAchievementProgress",
    "PlayerBattleData",
    "PlayerBattleRound",
    "PlayerClan",
    "PlayerItemLevel",
    "PlayerLeagueStatistics",
    "PlayerPathOfLegendRanking",
    "PlayerRanking",
    "PlayerRankingClan",
    "RegisterMatchRequest",
    "RegisterMatchResponse",
    "Replay",
    "RiverRaceClan",
    "RiverRaceLogEntry",
    "RiverRaceParticipant",
    "RiverRaceStanding",
    "SurvivalMilestoneReward",
    "Tournament",
    "TournamentHeader",
    "TournamentMember",
    "UpcomingChests",
    "VerifyTokenRequest",
    "VerifyTokenResponse",
    "Version",
]

# import apis into sdk package
from clashroyale.api.cards_api import CardsApi as CardsApi
from clashroyale.api.challenges_api import ChallengesApi as ChallengesApi
from clashroyale.api.clans_api import ClansApi as ClansApi
from clashroyale.api.globaltournaments_api import GlobaltournamentsApi as GlobaltournamentsApi
from clashroyale.api.leaderboards_api import LeaderboardsApi as LeaderboardsApi
from clashroyale.api.locations_api import LocationsApi as LocationsApi
from clashroyale.api.players_api import PlayersApi as PlayersApi
from clashroyale.api.tournaments_api import TournamentsApi as TournamentsApi


# import ApiClient
from clashroyale.api_response import ApiResponse as ApiResponse
from clashroyale.api_client import ApiClient as ApiClient
from clashroyale.configuration import Configuration as Configuration
from clashroyale.exceptions import OpenApiException as OpenApiException
from clashroyale.exceptions import ApiTypeError as ApiTypeError
from clashroyale.exceptions import ApiValueError as ApiValueError
from clashroyale.exceptions import ApiKeyError as ApiKeyError
from clashroyale.exceptions import ApiAttributeError as ApiAttributeError
from clashroyale.exceptions import ApiException as ApiException

# import models into sdk package
from clashroyale.models.arena import Arena as Arena
from clashroyale.models.battle import Battle as Battle
from clashroyale.models.cancel_match_response import CancelMatchResponse as CancelMatchResponse
from clashroyale.models.challenge import Challenge as Challenge
from clashroyale.models.challenge_chain import ChallengeChain as ChallengeChain
from clashroyale.models.challenge_game_mode import ChallengeGameMode as ChallengeGameMode
from clashroyale.models.chest import Chest as Chest
from clashroyale.models.clan import Clan as Clan
from clashroyale.models.clan_member import ClanMember as ClanMember
from clashroyale.models.clan_ranking import ClanRanking as ClanRanking
from clashroyale.models.clan_war_clan import ClanWarClan as ClanWarClan
from clashroyale.models.clan_war_log_entry import ClanWarLogEntry as ClanWarLogEntry
from clashroyale.models.clan_war_participant import ClanWarParticipant as ClanWarParticipant
from clashroyale.models.clan_war_standing import ClanWarStanding as ClanWarStanding
from clashroyale.models.client_error import ClientError as ClientError
from clashroyale.models.current_clan_war import CurrentClanWar as CurrentClanWar
from clashroyale.models.current_river_race import CurrentRiverRace as CurrentRiverRace
from clashroyale.models.emote import Emote as Emote
from clashroyale.models.fingerprint import Fingerprint as Fingerprint
from clashroyale.models.game_mode import GameMode as GameMode
from clashroyale.models.item import Item as Item
from clashroyale.models.items import Items as Items
from clashroyale.models.ladder_tournament import LadderTournament as LadderTournament
from clashroyale.models.ladder_tournament_ranking import LadderTournamentRanking as LadderTournamentRanking
from clashroyale.models.leaderboard import Leaderboard as Leaderboard
from clashroyale.models.league_season import LeagueSeason as LeagueSeason
from clashroyale.models.league_season_result import LeagueSeasonResult as LeagueSeasonResult
from clashroyale.models.location import Location as Location
from clashroyale.models.match import Match as Match
from clashroyale.models.path_of_legend_season_result import PathOfLegendSeasonResult as PathOfLegendSeasonResult
from clashroyale.models.period_log import PeriodLog as PeriodLog
from clashroyale.models.period_log_entry import PeriodLogEntry as PeriodLogEntry
from clashroyale.models.period_log_entry_clan import PeriodLogEntryClan as PeriodLogEntryClan
from clashroyale.models.player import Player as Player
from clashroyale.models.player_achievement_badge import PlayerAchievementBadge as PlayerAchievementBadge
from clashroyale.models.player_achievement_progress import PlayerAchievementProgress as PlayerAchievementProgress
from clashroyale.models.player_battle_data import PlayerBattleData as PlayerBattleData
from clashroyale.models.player_battle_round import PlayerBattleRound as PlayerBattleRound
from clashroyale.models.player_clan import PlayerClan as PlayerClan
from clashroyale.models.player_item_level import PlayerItemLevel as PlayerItemLevel
from clashroyale.models.player_league_statistics import PlayerLeagueStatistics as PlayerLeagueStatistics
from clashroyale.models.player_path_of_legend_ranking import PlayerPathOfLegendRanking as PlayerPathOfLegendRanking
from clashroyale.models.player_ranking import PlayerRanking as PlayerRanking
from clashroyale.models.player_ranking_clan import PlayerRankingClan as PlayerRankingClan
from clashroyale.models.register_match_request import RegisterMatchRequest as RegisterMatchRequest
from clashroyale.models.register_match_response import RegisterMatchResponse as RegisterMatchResponse
from clashroyale.models.replay import Replay as Replay
from clashroyale.models.river_race_clan import RiverRaceClan as RiverRaceClan
from clashroyale.models.river_race_log_entry import RiverRaceLogEntry as RiverRaceLogEntry
from clashroyale.models.river_race_participant import RiverRaceParticipant as RiverRaceParticipant
from clashroyale.models.river_race_standing import RiverRaceStanding as RiverRaceStanding
from clashroyale.models.survival_milestone_reward import SurvivalMilestoneReward as SurvivalMilestoneReward
from clashroyale.models.tournament import Tournament as Tournament
from clashroyale.models.tournament_header import TournamentHeader as TournamentHeader
from clashroyale.models.tournament_member import TournamentMember as TournamentMember
from clashroyale.models.upcoming_chests import UpcomingChests as UpcomingChests
from clashroyale.models.verify_token_request import VerifyTokenRequest as VerifyTokenRequest
from clashroyale.models.verify_token_response import VerifyTokenResponse as VerifyTokenResponse
from clashroyale.models.version import Version as Version
